### ISSUE TITLE
[BUG]can not complie 

### ISSUE THREAD

**Issue by gyb997** [richerarc/saphir#80]
**Description**
saphir v2.6.7
error[E0277]: the trait bound `hyper::body::body::Body: std::convert::From<std::boxed::Box<dyn futures_core::stream::Stream<Item = std::result::Result<bytes::bytes::Bytes, std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>> + std::marker::Send + std::marker::Sync>>` is not satisfied
   --> /home/guoyibin3/.cargo/registry/src/github.com-1ecc6299db9ec823/saphir-2.6.7/src/response.rs:374:18
    |
374 |             self.body(Box::new(file.into())
    |                  ^^^^ the trait `std::convert::From<std::boxed::Box<dyn futures_core::stream::Stream<Item = std::result::Result<bytes::bytes::Bytes, std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>> + std::marker::Send + std::marker::Sync>>` is not implemented for `hyper::body::body::Body`
    |
    = help: the following implementations were found:
              <hyper::body::body::Body as std::convert::From<&'static [u8]>>
              <hyper::body::body::Body as std::convert::From<&'static str>>
              <hyper::body::body::Body as std::convert::From<bytes::bytes::Bytes>>
              <hyper::body::body::Body as std::convert::From<std::borrow::Cow<'static, [u8]>>>
            and 4 others
    = note: required because of the requirements on the impl of `std::convert::Into<hyper::body::body::Body>` for `std::boxed::Box<dyn futures_core::stream::Stream<Item = std::result::Result<bytes::bytes::Bytes, std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>> + std::marker::Send + std::marker::Sync>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `saphir`.
**Expected behavior**

**Additional info (please complete the following information):**
 - OS & OS Version: [ubuntu 20]
 - Saphir Version [2.0.0]
 - Rust toolchain & version [1.43.1 (8d69840ab 2020-05-04)
]

**Comment by richerarc** [comment]
Hi @gyb997, first thanks for reporting this! 
I just release version 2.6.8 which fixes the build issue.

**Comment by gyb997** [comment]
Thx a lot
